name: CI

on: [push, pull_request]
jobs:
  build-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: brew upgrade
      run: brew upgrade

    - name: install make
      run: brew install make

    - name: install gcc
      run: brew reinstall gcc@14

    - name: make toolchain
      run: sh toolchain.sh

    - name: upload binutils.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: ar
        path: toolchain/bin/binutils/binutils.tar.gz
  


  
