name: CI

on: [push, pull_request]
jobs:
  build-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: brew upgrade
      run: brew upgrade

    - name: install make
      run: brew install make

    - name: install gcc
      run: brew install gcc@14

    - name: make toolchain
      run: sh toolchain.sh

    - name: upload binutils configure.log
      uses: actions/upload-artifact@v4
      with:
        name: binutils-configure.log
        path: binutils-2.37/configure.log

    - name: upload gcc configure.log
      uses: actions/upload-artifact@v4
      with:
        name: gcc-configure.log
        path: gcc-4.9.0/configure.log
  
